# Use postgres/example user/password credentials
version: "3.1"

services:
  moma-api:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: moma-api
    networks:
      - moma-network
    ports:
      - 9000:9000
    volumes:
      - ./application:/var/www/
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    restart: always
    environment:
      - APP_ENV=local
      - DB_CONNECTION=pgsql
      - DB_HOST=moma-db
      - DB_PORT=5432
      - DB_DATABASE=moma
      - DB_USERNAME=root
      - DB_PASSWORD=

  moma-db:
    image: postgres:13.1
    container_name: moma-db
    networks:
      - moma-network
    volumes:
      - moma-db-volume:/var/lib/postgresql/data
    ports:
      - 55432:5432
    restart: always
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: root
      POSTGRES_PASSWORD:
      POSTGRES_DB: moma
      POSTGRES_HOST_AUTH_METHOD: trust
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    logging:
      options:
        max-size: "10k"
        max-file: "5"

networks:
  moma-network:
    name: moma-network

volumes:
  moma-db-volume:
    name: moma-db-volume
